import { systemMetricsDictType } from 'types/utils/formatSystemMetricName';

export const systemMetricsDict: systemMetricsDictType = {
  'system/cpu_utilization_percentage': 'CPU (%)',
  'system/disk_available_megabytes': 'Disk Available (MB)',
  'system/disk_usage_megabytes': 'Disk (MB)',
  'system/disk_usage_percentage': 'Disk (%)',
  'system/gpu_0_memory_usage_megabytes': 'GPU 0 Memory (MB)',
  'system/gpu_0_memory_usage_percentage': 'GPU 0 Memory (%)',
  'system/gpu_0_power_usage_percentage': 'GPU 0 Power (%)',
  'system/gpu_0_power_usage_watts': 'GPU 0 Watts',
  'system/gpu_0_utilization_percentage': 'GPU 0 (%)',
  'system/gpu_1_memory_usage_megabytes': 'GPU 1 Memory (MB)',
  'system/gpu_1_memory_usage_percentage': 'GPU 1 Memory (%)',
  'system/gpu_1_power_usage_percentage': 'GPU 1 Power (%)',
  'system/gpu_1_power_usage_watts': 'GPU 1 Watts',
  'system/gpu_1_utilization_percentage': 'GPU 1 (%)',
  'system/gpu_2_memory_usage_megabytes': 'GPU 2 Memory (MB)',
  'system/gpu_2_memory_usage_percentage': 'GPU 2 Memory (%)',
  'system/gpu_2_power_usage_percentage': 'GPU 2 Power (%)',
  'system/gpu_2_power_usage_watts': 'GPU 2 Watts',
  'system/gpu_2_utilization_percentage': 'GPU 2 (%)',
  'system/gpu_3_memory_usage_megabytes': 'GPU 3 Memory (MB)',
  'system/gpu_3_memory_usage_percentage': 'GPU 3 Memory (%)',
  'system/gpu_3_power_usage_percentage': 'GPU 3 Power (%)',
  'system/gpu_3_power_usage_watts': 'GPU 3 Watts',
  'system/gpu_3_utilization_percentage': 'GPU 3 (%)',
  'system/gpu_4_memory_usage_megabytes': 'GPU 4 Memory (MB)',
  'system/gpu_4_memory_usage_percentage': 'GPU 4 Memory (%)',
  'system/gpu_4_power_usage_percentage': 'GPU 4 Power (%)',
  'system/gpu_4_power_usage_watts': 'GPU 4 Watts',
  'system/gpu_4_utilization_percentage': 'GPU 4 (%)',
  'system/gpu_5_memory_usage_megabytes': 'GPU 5 Memory (MB)',
  'system/gpu_5_memory_usage_percentage': 'GPU 5 Memory (%)',
  'system/gpu_5_power_usage_percentage': 'GPU 5 Power (%)',
  'system/gpu_5_power_usage_watts': 'GPU 5 Watts',
  'system/gpu_5_utilization_percentage': 'GPU 5 (%)',
  'system/gpu_6_memory_usage_megabytes': 'GPU 6 Memory (MB)',
  'system/gpu_6_memory_usage_percentage': 'GPU 6 Memory (%)',
  'system/gpu_6_power_usage_percentage': 'GPU 6 Power (%)',
  'system/gpu_6_power_usage_watts': 'GPU 6 Watts',
  'system/gpu_6_utilization_percentage': 'GPU 6 (%)',
  'system/gpu_7_memory_usage_megabytes': 'GPU 7 Memory (MB)',
  'system/gpu_7_memory_usage_percentage': 'GPU 7 Memory (%)',
  'system/gpu_7_power_usage_percentage': 'GPU 7 Power (%)',
  'system/gpu_7_power_usage_watts': 'GPU 7 Watts',
  'system/gpu_7_utilization_percentage': 'GPU 7 (%)',
  'system/gpu_8_memory_usage_megabytes': 'GPU 8 Memory (MB)',
  'system/gpu_8_memory_usage_percentage': 'GPU 8 Memory (%)',
  'system/gpu_8_power_usage_percentage': 'GPU 8 Power (%)',
  'system/gpu_8_power_usage_watts': 'GPU 8 Watts',
  'system/gpu_8_utilization_percentage': 'GPU 8 (%)',
  'system/gpu_9_memory_usage_megabytes': 'GPU 9 Memory (MB)',
  'system/gpu_9_memory_usage_percentage': 'GPU 9 Memory (%)',
  'system/gpu_9_power_usage_percentage': 'GPU 9 Power (%)',
  'system/gpu_9_power_usage_watts': 'GPU 9 Watts',
  'system/gpu_9_utilization_percentage': 'GPU 9 (%)',
  'system/gpu_10_memory_usage_megabytes': 'GPU 10 Memory (MB)',
  'system/gpu_10_memory_usage_percentage': 'GPU 10 Memory (%)',
  'system/gpu_10_power_usage_percentage': 'GPU 10 Power (%)',
  'system/gpu_10_power_usage_watts': 'GPU 10 Watts',
  'system/gpu_10_utilization_percentage': 'GPU 10 (%)',
  'system/gpu_11_memory_usage_megabytes': 'GPU 11 Memory (MB)',
  'system/gpu_11_memory_usage_percentage': 'GPU 11 Memory (%)',
  'system/gpu_11_power_usage_percentage': 'GPU 11 Power (%)',
  'system/gpu_11_power_usage_watts': 'GPU 11 Watts',
  'system/gpu_11_utilization_percentage': 'GPU 11 (%)',
  'system/gpu_12_memory_usage_megabytes': 'GPU 12 Memory (MB)',
  'system/gpu_12_memory_usage_percentage': 'GPU 12 Memory (%)',
  'system/gpu_12_power_usage_percentage': 'GPU 12 Power (%)',
  'system/gpu_12_power_usage_watts': 'GPU 12 Watts',
  'system/gpu_12_utilization_percentage': 'GPU 12 (%)',
  'system/gpu_13_memory_usage_megabytes': 'GPU 13 Memory (MB)',
  'system/gpu_13_memory_usage_percentage': 'GPU 13 Memory (%)',
  'system/gpu_13_power_usage_percentage': 'GPU 13 Power (%)',
  'system/gpu_13_power_usage_watts': 'GPU 13 Watts',
  'system/gpu_13_utilization_percentage': 'GPU 13 (%)',
  'system/gpu_14_memory_usage_megabytes': 'GPU 14 Memory (MB)',
  'system/gpu_14_memory_usage_percentage': 'GPU 14 Memory (%)',
  'system/gpu_14_power_usage_percentage': 'GPU 14 Power (%)',
  'system/gpu_14_power_usage_watts': 'GPU 14 Watts',
  'system/gpu_14_utilization_percentage': 'GPU 14 (%)',
  'system/gpu_15_memory_usage_megabytes': 'GPU 15 Memory (MB)',
  'system/gpu_15_memory_usage_percentage': 'GPU 15 Memory (%)',
  'system/gpu_15_power_usage_percentage': 'GPU 15 Power (%)',
  'system/gpu_15_power_usage_watts': 'GPU 15 Watts',
  'system/gpu_15_utilization_percentage': 'GPU 15 (%)',
  'system/network_receive_megabytes': 'Network Rx (MB)',
  'system/network_transmit_megabytes': 'Network Tx (MB)',
  'system/system_memory_usage_megabytes': 'Memory (MB)',
  'system/system_memory_usage_percentage': 'Memory (%)',
};
