name: Playwright Tests
on:
  push:
    branches: [ main, master, release/* ]
  pull_request:
    branches: [ main, master, release/* ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16
    - name: Install dependencies
      run: cd src && npm ci --legacy-peer-deps
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Dev Server and E2E Tests
      run: cd src && npm start & npx playwright test
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
