name: Create release branch from main
on:
  push:
    branches:
      - main
    paths:
      - "upstream.txt"

jobs:
  create:
    name: Create release branch from main
    environment: restricted
    runs-on: ubuntu-latest
    steps:
      - name: Generate an app token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Checkout main repo
        uses: actions/checkout@v3
        with:
          path: main
          token: ${{ steps.generate_token.outputs.token }}
      - name: Read and check version
        id: version
        run: |
          version=$(cat main/upstream.txt)
          if ! [[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::error::Invalid version format. Expected vMAJOR.MINOR.PATCH"
            exit 1
          fi
          echo "version=${version}" >> "$GITHUB_OUTPUT"
      - name: Checkout upstream repo
        uses: actions/checkout@v3
        with:
          path: aim
          repository: aimhubio/aim
          ref: refs/tags/${{ steps.version.outputs.version }}
      - name: Add upstream UI to main repo
        run: mv aim/aim/web/ui main/src
      - name: Push
        working-directory: main
        run: |
          version=${{ steps.version.outputs.version }}
          git config user.name "FastTrackML CI"
          git config user.email "fasttrackml@gr-oss.io"
          git checkout -b release/$version
          git add src
          git commit -m "Import Aim UI $version"
          git push origin release/$version
